### PR TITLE
Make sure testcases only show up once

### LINKED ISSUE #13: It uses the description instead of the name so TestParams will not work because of duplicate names
```
It "Some test <ExpectedPath>" -TestCases @(@{ IsAdmin = $true; ExpectedPath = 'cert:\LocalMachine\My' },@{ IsAdmin = $false; ExpectedPath = 'cert:\CurrentUser\My' }) 
{
...
}
```
This result in two tests with the same name: **Some Test** because the description in **TestExplorerResults.xml** is **Some tests** where the name is **Some test cert:\LocalMachine\My** and **Some  test cert:\CurrentUser\My**

See the xml:
```
<test-case description="Some test" name="Some test.To run all the test cases.Some test(&quot;cert:\LocalMachine\My&quot;,True)" time="0.234" asserts="0" success="False" result="Failure" executed="True">
...
</test-case>
<test-case description="Some test" name="Some test.To run all the test cases.Some test(&quot;cert:\CurrentUser\My&quot;,False)" time="0.1041" asserts="0" success="False" result="Failure" executed="True">
....
</test-case>
```

Can this be configured (For example to let me choose it uses the name field instead of the description.)

### PR DESCRIPTION
**Pull request by TylerLeonhardt**
fixes #13 this makes `It`'s with `TestCases` only show up once in the tree view and all of the running works (if 1 test case fails, the test is considered failed)

### CODE REVIEW

File: src/powershellScripts.ts [hunk 1]
```diff
@@ -63,9 +63,16 @@ function fold ($children, $Block) {
         $children.Add($o)
         fold $o.children $b
     }
-    foreach ($t in $Block.Tests) { 
+
+    $hashset = [System.Collections.Generic.HashSet[string]]::new()
```
Comment (TylerLeonhardt) [inline src/powershellScripts.ts:67]: Makes sure we only add id's once
